include $(THEOS)/makefiles/common.mk

TOOL_NAME = termcalc

termcalc_FILES = Calculator+Memory.m Calculator+Ops.m Calculator.m main.m
termcalc_CFLAGS = -fobjc-arc
termcalc_FRAMEWORKS = Foundation 

include $(THEOS_MAKE_PATH)/tool.mk
